### PR TITLE
Greek (EL) translation

### PR DESCRIPTION
**Pull request by akritiko**
with this pull request I propose the translation of MyData declaration in Greek. Please consider accepting it. I remain at your disposal for any clarification you might need. 

Best regards and congratulation for your work.

A.

### CODE REVIEW

**Comment by apoikola** [comment]
Super, thanks @akritiko

**Comment by akritiko** [comment]
You are welcome @apoikola. Is it going to be featured to the website as well?

**Comment by apoikola** [comment]
@akritiko sure it will. If you can I would also welcome you to join MyData Global Slack http://mydata.org/slack there we have channel #declaration and also some fellow greek MyData members (I'm not sure yo know any of them). I just asked if someone could read trough the translation before putting it on web, but I'm sure that at lates by the MyData conference 25. Sep (https://mydata2019.org) it will be published.

**Comment by akritiko** [comment]
Just joined mydata slack. Thanks a lot for the invitation. Happy I helped :)

**Pull request merged**
